#-----------------------------------------------
#          Explosive Elytras Config
#-----------------------------------------------

#DO NOT CHANGE THIS VALUE.
#CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.0

#--------------[General Settings]---------------
general_settings:

  # A player must have at least one of the following
  # in their inventory at the time of crash in order
  # to explode. Leave this empty for no requirement.
  # Syntax is [id]:[data]|[amount]
  # Ex. 46:0|1 = 1 tnt, 289:0|64 = 64 gunpowder
  required_items:
    - "46:0|1"
    
  # The power of the explosion per required item found.
  # This will be the total power of the explosion if
  # the explosion multiplier is disabled.
  # The power of a single tnt explosion is 4.
  power_per_item: 4
    
  # If enabled the power of the explosion will increase
  # if you have more of a required item in your inventory.
  # The power will grow until it reaches the max power.
  # If disabled then the power of the explosion will be equal
  # to the power of one item (defined above).
  explosion_multiplier:
    enabled: true
    max_power: 16

  # Should the matching required item be consumed during
  # the explosion.
  consume_on_explosion: true
  
  # Should the elytra the player is wearing be consumed
  # during the explosion. This method is preferable to
  # simply adding the elytra to the required items list,
  # as only the chest plate slot is checked (ie only the
  # elytra currently worn will be consumed).
  consume_elytra_on_explosion: false
  
  # Should fireworks be launched when you explode from a crash.
  fireworks_on_explosion: true
  
  # Users will only blow up in the following worlds.
  # If left empty this plugin is essentially disabled.
  allowed_worlds:
    - world
    - world_nether
    - world_the_end
  
  # Choose a death message for explosive landings.
  # Use {0} for the player's name, color codes and
  # formatting are supported.
  death_message: "{0} had an explosive landing"

#---------[Horizontal Impact Settings]----------
# Settings for when a player crashes into something
# horizontally, like a wall.
horizontal_impact_settings:
  
  # Minimum damage on the player to cause an explosion.
  # 1 = .5 hearts, 2 = 1 heart, 3 = 1.5 hearts, etc.
  minimum_damage_value: 1
  
#---------[Vertical Impact Settings]----------
# Settings for when a player crashes into something
# verically, like the ground.
vertical_impact_settings:
  
  # Minimum damage on the player to cause an explosion.
  # 1 = .5 hearts, 2 = 1 heart, 3 = 1.5 hearts, etc.
  minimum_damage_value: 10