author: Daniel Scalzi
description: High speed elytra collisions cause explosions.
main: com.dscalzi.explosiveelytras.ExplosiveElytras
name: ExplosiveElytras
softdepend: [WorldGuard]
version: 0.9.2
commands:
  explosiveelytras:
    description: Main plugin command.
permissions:
  explosiveelytras.*:
    children:
      explosiveelytras.explode: true
      explosiveelytras.bypass.worldguard: true
      explosiveelytras.reload: true