author: Daniel Scalzi
description: High speed elytra collisions cause explosions.
main: com.dscalzi.explosiveelytras.internal.ExplosiveElytrasPlugin
name: ExplosiveElytras
api-version: 1.13
softdepend: [WorldGuard]
version: 0.11.2
commands:
  explosiveelytras:
    description: Main plugin command.
permissions:
  explosiveelytras.*:
    children:
      explosiveelytras.explode: true
      explosiveelytras.bypass.worldguard: true
      explosiveelytras.reload: true